name: Release
on:
  release:
    types: [released, edited]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GITHUB_SHA
        run: echo ${{ github.sha }}
      - name: Output GITHUB_REF
        run: echo ${{ github.ref }}
      - name: Output Tag Name
        run: echo ${{ github.event.release.tag_name }}
      - name: Output Action
        run: echo ${{ github.event.action }}
      - name: Output changes
        run: echo "${{ toJson(github.event.changes) }}"
      - name: Output GITHUB
        run: echo "${{ toJson(github) }}"
      - name: Output GITHUB_EVENT
        run: echo "${{ toJson(github.event) }}"
      - name: Get the code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - name: Output dir
        run: ls -la