name: Release
on:
  release:
    types: [released, edited]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GITHUB_SHA
        run: echo ${{ github.sha }}
      - name: Output GITHUB_REF
        run: echo ${{ github.ref }}
      - name: Output Tag NAme
        run: echo ${{ github.event.tag_name }}
      - name: Output GITHUB_REF
        run: echo "${{ toJson(github) }}"
      - name: Output GITHUB_REF
        run: echo "${{ toJson(github.event) }}"